In [2]:
import pandas as pd

In [3]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_10 - Copy.csv")

In [4]:
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [5]:
import pandas as pd

scalar_s = pd.Series(1)
print(scalar_s)

0    1
dtype: int64

In [6]:
dict_s = pd.Series({'a':1,'b':2})
dict_s

a    1
b    2
dtype: int64

In [7]:
dict2 = {'ID':[1,2,2]}

In [8]:
series_2 = pd.Series([1,2,3,4],index = ['o','k','o','k'],dtype = float,name = 'data')
print(series_2)

o    1.0
k    2.0
o    3.0
k    4.0
Name: data, dtype: float64

In [9]:
sr_indx = pd.Series([1,2,3,4,5])
print(sr_indx)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [10]:
sr_indx[0]

np.int64(1)

In [11]:
sr_indx[1]

np.int64(2)

In [12]:
min(sr_indx)

1

In [13]:
sr_indx[sr_indx>2]

2    3
3    4
4    5
dtype: int64

In [14]:
sr_indx[sr_indx<2]

0    1
dtype: int64

In [15]:
sr1 = pd.Series([1,2,3,4,5])
sr2 = pd.Series([6,7,8,9,10])
print(sr1)
print(sr2)

sum = sr1 + sr2
print(sum)

sr3 = pd.Series([1,2,3])
sr_sum_unq = sr2+sr3
print(sr_sum_unq)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0     6
1     7
2     8
3     9
4    10
dtype: int64
0     7
1     9
2    11
3    13
4    15
dtype: int64
0     7.0
1     9.0
2    11.0
3     NaN
4     NaN
dtype: float64

In [16]:
empt_df = pd.DataFrame()
print(empt_df)

Empty DataFrame
Columns: []
Index: []

In [17]:
import os
print(os.getcwd())

C:\Users\Sephanya

In [18]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_10 - Copy.csv", nrows = 1)
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%

In [19]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_10 - Copy.csv")
df.columns

Index(['ID', 'Name', 'Industry', 'Inception', 'Revenue', 'Expenses', 'Profit',
       'Growth'],
      dtype='object')

In [20]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_10 - Copy.csv", usecols =[1,2])
df

              Name             Industry
0          Lamtone          IT Services
1        Stripfind   Financial Services
2  Canecorporation               Health
3         Mattouch          IT Services
4        Techdrill               Health
5         Techline               Health
6          Cityace               Health
7   Kayelectronics               Health
8          Ganzlax          IT Services
9      Trantraxlax  Government Services

In [21]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_10 - Copy.csv", skiprows = [1,2,3,4])
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
1,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
2,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
3,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
4,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
5,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [22]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_10 - Copy.csv", index_col = "Industry")
df

,ID,Name,Inception,Revenue,Expenses,Profit,Growth
Industry,,,,,,,
IT Services,1,Lamtone,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
Financial Services,2,Stripfind,2010,"$12,329,371","916,455 Dollars",11412916,20%
Health,3,Canecorporation,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
IT Services,4,Mattouch,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
Health,5,Techdrill,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
Health,6,Techline,2006,no value,"5,470,303 Dollars",8427816,23%
Health,7,Cityace,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
Health,8,Kayelectronics,2009,na,"3,878,113 Dollars",5573830,4%
IT Services,9,Ganzlax,2011,"$14,001,180",NaN,11901180,18%
Government Services,10,Trantraxlax,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [23]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_10 - Copy.csv", index_col = 3)
df

,ID,Name,Industry,Revenue,Expenses,Profit,Growth
Inception,,,,,,,
2009,1,Lamtone,IT Services,"$11,757,018","6,482,465 Dollars",5274553,30%
2010,2,Stripfind,Financial Services,"$12,329,371","916,455 Dollars",11412916,20%
2012,3,Canecorporation,Health,"$10,597,009","7,591,189 Dollars",3005820,7%
2013,4,Mattouch,IT Services,"$14,026,934","7,429,377 Dollars",6597557,not available
2009,5,Techdrill,Health,"$10,573,990","7,435,363 Dollars",3138627,8%
2006,6,Techline,Health,no value,"5,470,303 Dollars",8427816,23%
2010,7,Cityace,Health,"$9,254,614","6,249,498 Dollars",3005116,not available
2009,8,Kayelectronics,Health,na,"3,878,113 Dollars",5573830,4%
2011,9,Ganzlax,IT Services,"$14,001,180",NaN,11901180,18%
2011,10,Trantraxlax,Government Services,"$11,088,336","5,635,276 Dollars",5453060,7%

In [24]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_10 - Copy.csv", header = 1)
df

,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
0,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
1,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
2,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
3,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
4,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
5,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
6,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
7,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
8,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [25]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_10 - Copy.csv", header = 5)
df

,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
0,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
1,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
2,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
3,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
4,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [26]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_10 - Copy.csv", names = ['A','B'])
df

,,,,,,A,B
ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [27]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_10 - Copy.csv", dtype = {'ID':'float64','profit':'float64'})
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3.0,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4.0,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5.0,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6.0,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7.0,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8.0,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10.0,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [28]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_10 - Copy.csv", dtype = {'Inception':'float64'})
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006.0,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010.0,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009.0,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011.0,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060,7%

In [29]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_10 - Copy.csv")
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [30]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_10 - Copy.csv", na_values = 'not available')
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,NaN
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,NaN
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [31]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_10 - Copy.csv", na_values = {'Revenue' : 'no value'})
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,NaN,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [32]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_10 - Copy.csv", na_values = {'Revenue' : 'no value'})
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,NaN,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [33]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_10 - Copy.csv", keep_default_na = True)
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [34]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_10 - Copy.csv", na_filter = False)
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [35]:
df.isnull()

      ID   Name  Industry  Inception  Revenue  Expenses  Profit  Growth
0  False  False     False      False    False     False   False   False
1  False  False     False      False    False     False   False   False
2  False  False     False      False    False     False   False   False
3  False  False     False      False    False     False   False   False
4  False  False     False      False    False     False   False   False
5  False  False     False      False    False     False   False   False
6  False  False     False      False    False     False   False   False
7  False  False     False      False    False     False   False   False
8  False  False     False      False    False     False   False   False
9  False  False     False      False    False     False   False   False

In [36]:
df.notnull()

     ID  Name  Industry  Inception  Revenue  Expenses  Profit  Growth
0  True  True      True       True     True      True    True    True
1  True  True      True       True     True      True    True    True
2  True  True      True       True     True      True    True    True
3  True  True      True       True     True      True    True    True
4  True  True      True       True     True      True    True    True
5  True  True      True       True     True      True    True    True
6  True  True      True       True     True      True    True    True
7  True  True      True       True     True      True    True    True
8  True  True      True       True     True      True    True    True
9  True  True      True       True     True      True    True    True

In [37]:
import numpy as np

ser = pd.Series([1,2,3,np.nan,4,np.nan])
ser
ser.notnull()

0     True
1     True
2     True
3    False
4     True
5    False
dtype: bool

In [38]:
ser.isnull()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [39]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_5 nan values.csv")
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Sephanya\Downloads\Fortune_5 nan values.csv")
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
df.dropna()

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [42]:
df.dropna(axis = 0)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [43]:
df.dropna(how = 'any')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [44]:
df.dropna(axis = 1,how = 'any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
df.dropna(how = 'all')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%

In [46]:
df.dropna(thresh = 0)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
df.dropna(thresh = 2)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%

In [48]:
df.dropna(thresh = 1)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%

In [49]:
df.dropna(subset = ['Profit'])

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [50]:
df.dropna(subset = ['Expenses'])

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%

In [51]:
df.fillna({'Expenses':'none','Profit':55})

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",none,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",55.0,8%
5,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN
6,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN
7,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN
8,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN
9,NaN,NaN,NaN,NaN,NaN,none,55.0,NaN

In [52]:
df.fillna(method = 'ffill')

C:\Users\Sephanya\AppData\Local\Temp\ipykernel_14928\1145651979.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009","916,455 Dollars",3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
5,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
6,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
7,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
8,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%
9,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",6597557.0,8%

In [53]:
df.fillna(method = 'bfill')

C:\Users\Sephanya\AppData\Local\Temp\ipykernel_14928\3673297803.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'bfill')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009","7,429,377 Dollars",3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
df.replace(to_replace = 'Health', value = 'it serv')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,it serv,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,it serv,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
df.replace(10,15)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
df.replace({'industry':'Health'},'nan')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
df["ID"] = df["ID"].astype("Int64")
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
df.replace({"Industry": "[A-Za-z]"}, 0, regex=True)

C:\Users\Sephanya\AppData\Local\Temp\ipykernel_14928\956828490.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({"Industry": "[A-Za-z]"}, 0, regex=True)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,0.0,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Stripfind,0.0,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,Canecorporation,0.0,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4,Mattouch,0.0,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Techdrill,0.0,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
df.replace('Health',method='ffill')

C:\Users\Sephanya\AppData\Local\Temp\ipykernel_14928\3424027052.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace('Health',method='ffill')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,Canecorporation,Financial Services,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Techdrill,IT Services,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN